### ISSUE TITLE
 Failed to execute CommandLineRunner

### ISSUE THREAD

**Issue by zhongfox** [crossoverJie/blog.toolbox#6]
问题一: test代码里有硬编码: /Users/chenjie/Documents 导致测试不通过.

问题二: 跳过测试后编译成功, 运行遇到报错

2019-05-13 10:36:03.318 ERROR 3927 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at top.crossoverjie.nows.nows.NowsApplication.main(NowsApplication.java:51) [classes!/:0.0.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [blog.toolbox-0.0.2.jar:0.0.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [blog.toolbox-0.0.2.jar:0.0.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [blog.toolbox-0.0.2.jar:0.0.2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [blog.toolbox-0.0.2.jar:0.0.2]
Caused by: java.lang.NullPointerException: null
	at top.crossoverjie.nows.nows.scan.ScannerFile.getAllFile(ScannerFile.java:25) ~[classes!/:0.0.2]
	at top.crossoverjie.nows.nows.scan.ScannerFile.getAllFile(ScannerFile.java:28) ~[classes!/:0.0.2]
	at top.crossoverjie.nows.nows.NowsApplication.run(NowsApplication.java:73) [classes!/:0.0.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	... 14 common frames omitted

**Comment by crossoverJie** [comment]
@zhongfox 
1. 单测目前没有 `mock` ，所以编译时需要跳过测试。
2. 请提供下启动命令。
