### ISSUE TITLE
Windows环境下文件路径问题

### ISSUE THREAD

**Issue by zzzzbw** [crossoverJie/blog.toolbox#7]
windows环境下路径拼接会有问题导致图片下载不到指定路径

执行命令: `java -jar blog.toolbox-0.0.2.jar E:/zbw/develop/blogs 200 --app.model=3 --app.downLoad.path=E:/zbw/develop/backup`

```
2019-05-14 16:10:38.566 ERROR 10136 --- [         task-1] t.c.nows.nows.thread.ScanTask            : 下载图片失败 fileName=[E:/zbw/develop/backups/E:\zbw\develop\blogs\Spring-boot+Vue = Fame 写blog的一次小结.md---Fame-front-article-detail.png]

java.io.FileNotFoundException: E:\zbw\develop\backups\E:\zbw\develop\blogs\Spring-boot+Vue = Fame 写blog的一次小结.md---Fame-front-article-detail.png (文件名、目录名或卷标语法不正确。)
        at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_71]
        at java.io.FileOutputStream.open(Unknown Source) ~[na:1.8.0_71]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_71]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_71]
        at top.crossoverjie.nows.nows.util.DownloadUploadPic.download(DownloadUploadPic.java:55) ~[classes!/:0.0.2]
        at top.crossoverjie.nows.nows.thread.ScanTask.downUpPic(ScanTask.java:166) [classes!/:0.0.2]
        at top.crossoverjie.nows.nows.thread.ScanTask.run(ScanTask.java:67) [classes!/:0.0.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_71]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]

```

**Comment by crossoverJie** [comment]
@zzzzbw 

已经解决，可以更新打包或者下载 `release` 包再试试。

https://github.com/crossoverJie/blog.toolbox/releases/download/v0.0.2/blog.toolbox-0.0.2.jar

**Comment by zzzzbw** [comment]
可以了, Thx
